=== patelkrupali010/Data-Engineering-Project/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "installationId": {
        "type": "number"
      },
      "siteModel": {
        "type": "object",
        "properties": {
          "buildings": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "mountingPlanes": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "number"
                      },
                      "area": {
                        "type": "number"
                      },
                      "pitchAngle": {
                        "type": "number"
                      },
                      "azimuthAngle": {
                        "type": "number"
                      },
                      "azimuthVector": {
                        "type": "object",
                        "properties": {
                          "x": {
                            "type": "number"
                          },
                          "y": {
                            "type": "number"
                          },
                          "z": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "x",
                          "y",
                          "z"
                        ]
                      },
                      "roofMaterialType": {
                        "type": "string"
                      },
                      "centroid": {
                        "type": "object",
                        "properties": {
                          "x": {
                            "type": "number"
                          },
                          "y": {
                            "type": "number"
                          },
                          "z": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "x",
                          "y",
                          "z"
                        ]
                      },
                      "coordinateSystem": {
                        "type": "object",
                        "properties": {
                          "xAxis": {
                            "type": "object",
                            "properties": {
                              "x": {
                                "type": "number"
                              },
                              "y": {
                                "type": "number"
                              },
                              "z": {
                                "type": "number"
                              }
                            },
                            "required": [
                              "x",
                              "y",
                              "z"
                            ]
                          },
                          "yAxis": {
                            "type": "object",
                            "properties": {
                              "x": {
                                "type": "number"
                              },
                              "y": {
                                "type": "number"
                              },
                              "z": {
                                "type": "number"
                              }
                            },
                            "required": [
                              "x",
                              "y",
                              "z"
                            ]
                          },
                          "zAxis": {
                            "type": "object",
                            "properties": {
                              "x": {
                                "type": "number"
                              },
                              "y": {
                                "type": "number"
                              },
                              "z": {
                                "type": "number"
                              }
                            },
                            "required": [
                              "x",
                              "y",
                              "z"
                            ]
                          }
                        },
                        "required": [
                          "xAxis",
                          "yAxis",
                          "zAxis"
                        ]
                      },
                      "polygon": {
                        "type": "object",
                        "properties": {
                          "exteriorRing": {
                            "type": "object",
                            "properties": {
                              "windingDirection": {},
                              "edges": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "id": {
                                      "type": "number"
                                    },
                                    "startPoint": {
                                      "type": "object",
                                      "properties": {
                                        "x": {
                                          "type": "number"
                                        },
                                        "y": {
                                          "type": "number"
                                        },
                                        "z": {
                                          "type": "number"
                                        }
                                      },
                                      "required": [
                                        "x",
                                        "y",
                                        "z"
                                      ]
                                    },
                                    "endPoint": {
                                      "type": "object",
                                      "properties": {
                                        "x": {
                                          "type": "number"
                                        },
                                        "y": {
                                          "type": "number"
                                        },
                                        "z": {
                                          "type": "number"
                                        }
                                      },
                                      "required": [
                                        "x",
                                        "y",
                                        "z"
                                      ]
                                    },
                                    "bearingVector": {},
                                    "angleBetweenBearingVectorAndUpVector": {
                                      "type": "number"
                                    },
                                    "angleBetweenBearingVectorAndRightVector": {
                                      "type": "number"
                                    },
                                    "edgeCondition": {
                                        "anyOf": [
                                            {
                                                "type": "string"
                                            },
                                            {
                                                "type": "null"
                                            }
                                        ]
                                    },
                                    "sidingMaterial": {}
                                  },
                                  "required": [
                                    "id",
                                    "startPoint",
                                    "endPoint",
                                    "bearingVector",
                                    "angleBetweenBearingVectorAndUpVector",
                                    "angleBetweenBearingVectorAndRightVector",
                                    "edgeCondition",
                                    "sidingMaterial"
                                  ]
                                }
                              }
                            },
                            "required": [
                              "windingDirection",
                              "edges"
                            ]
                          },
                          "interiorRings": {
                            "type": "array",
                            "items": {}
                          }
                        },
                        "required": [
                          "exteriorRing",
                          "interiorRings"
                        ]
                      },
                      "obstructions": {},
                      "penetrations": {}
                    },
                    "required": [
                      "id",
                      "area",
                      "pitchAngle",
                      "azimuthAngle",
                      "azimuthVector",
                      "roofMaterialType",
                      "centroid",
                      "coordinateSystem",
                      "polygon",
                      "obstructions",
                      "penetrations"
                    ]
                  }
                },
                "isPrimaryBuilding": {
                  "type": "boolean"
                },
                "totalRoofArea": {
                  "type": "number"
                },
                "polygon": {
                  "type": "object",
                  "properties": {
                    "exteriorRing": {
                      "type": "object",
                      "properties": {
                        "windingDirection": {},
                        "edges": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "startPoint": {
                                "type": "object",
                                "properties": {
                                  "x": {
                                    "type": "number"
                                  },
                                  "y": {
                                    "type": "number"
                                  },
                                  "z": {
                                    "type": "number"
                                  }
                                },
                                "required": [
                                  "x",
                                  "y",
                                  "z"
                                ]
                              },
                              "endPoint": {
                                "type": "object",
                                "properties": {
                                  "x": {
                                    "type": "number"
                                  },
                                  "y": {
                                    "type": "number"
                                  },
                                  "z": {
                                    "type": "number"
                                  }
                                },
                                "required": [
                                  "x",
                                  "y",
                                  "z"
                                ]
                              },
                              "bearingVector": {},
                              "angleBetweenBearingVectorAndUpVector": {
                                "type": "number"
                              },
                              "angleBetweenBearingVectorAndRightVector": {
                                "type": "number"
                              },
                              "edgeCondition": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "null"
                                    }
                                ]
                              },
                              "sidingMaterial": {}
                            },
                            "required": [
                              "id",
                              "startPoint",
                              "endPoint",
                              "bearingVector",
                              "angleBetweenBearingVectorAndUpVector",
                              "angleBetweenBearingVectorAndRightVector",
                              "edgeCondition",
                              "sidingMaterial"
                            ]
                          }
                        }
                      },
                      "required": [
                        "windingDirection",
                        "edges"
                      ]
                    },
                    "interiorRings": {
                      "type": "array",
                      "items": {}
                    }
                  },
                  "required": [
                    "exteriorRing",
                    "interiorRings"
                  ]
                }
              },
              "required": [
                "mountingPlanes",
                "isPrimaryBuilding",
                "totalRoofArea",
                "polygon"
              ]
            }
          },
          "units": {
            "type": "object",
            "properties": {
              "length": {
                "type": "string"
              },
              "angle": {
                "type": "string"
              },
              "area": {
                "type": "string"
              }
            },
            "required": [
              "length",
              "angle",
              "area"
            ]
          },
          "northVector": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "z": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y",
              "z"
            ]
          },
          "headingVector": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "z": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y",
              "z"
            ]
          },
          "version": {
            "type": "string"
          },
          "obstructions": {}
        },
        "required": [
          "buildings",
          "units",
          "northVector",
          "headingVector",
          "version",
          "obstructions"
        ]
      },
      "dateCreated": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "externalSiteModelSourceId": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "installationId",
      "siteModel",
      "dateCreated",
      "version",
      "externalSiteModelSourceId"
    ]
  }

=== patelkrupali010/Data-Engineering-Project/roof_input_data/roof_4.json
{"id":4,"installationId":4,"siteModel":{"buildings":[{"mountingPlanes":[{"id":0,"area":407.82296691427536,"pitchAngle":44.999999998151985,"azimuthAngle":67.0,"azimuthVector":{"x":1.0,"y":2.3547402041039343E-27,"z":0.0},"roofMaterialType":"CompShingle","centroid":{"x":374.822438892,"y":-173.94226237799998,"z":62.007997916},"coordinateSystem":{"xAxis":{"x":2.2204460492267656E-16,"y":1.0,"z":0.0},"yAxis":{"x":-0.7071067812093544,"y":1.570092458717766E-16,"z":0.7071067811637405},"zAxis":{"x":0.7071067811637405,"y":1.6650527662007825E-27,"z":0.7071067812093544}},"polygon":{"exteriorRing":{"windingDirection":null,"edges":[{"id":0,"startPoint":{"x":436.830436812,"y":49.2865301220001,"z":0.0},"endPoint":{"x":436.830436812,"y":-397.171054878,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":1,"startPoint":{"x":436.830436812,"y":-397.171054878,"z":0.0},"endPoint":{"x":250.806443052,"y":-173.942262378,"z":186.023993748},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":2,"startPoint":{"x":250.806443052,"y":-173.942262378,"z":186.023993748},"endPoint":{"x":436.830436812,"y":49.2865301220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null}]},"interiorRings":[]},"obstructions":null,"penetrations":null},{"id":1,"area":647.09858796737,"pitchAngle":39.80557109209468,"azimuthAngle":337.0,"azimuthVector":{"x":7.974427234451834E-13,"y":1.0,"z":0.0},"roofMaterialType":"CompShingle","centroid":{"x":144.9187100382857,"y":-32.771799652285644,"z":68.38194147942858},"coordinateSystem":{"xAxis":{"x":-1.0,"y":7.976647680501087E-13,"z":0.0},"yAxis":{"x":-6.127830488016546E-13,"y":-0.7682212795979478,"z":0.6401843996637935},"zAxis":{"x":5.105103911750155E-13,"y":0.6401843996637935,"z":0.7682212795979478}},"polygon":{"exteriorRing":{"windingDirection":null,"edges":[{"id":3,"startPoint":{"x":250.806443052,"y":-173.942262378,"z":186.023993748},"endPoint":{"x":436.830436812,"y":49.2865301220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":4,"startPoint":{"x":436.830436812,"y":49.2865301220001,"z":0.0},"endPoint":{"x":240.873874296,"y":49.2865301220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":5,"startPoint":{"x":240.873874296,"y":49.2865301220001,"z":0.0},"endPoint":{"x":134.248271436,"y":-78.6641932979999,"z":106.62560286},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":6,"startPoint":{"x":134.248271436,"y":-78.6641932979999,"z":106.62560286},"endPoint":{"x":27.6226685879999,"y":49.2865301220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":7,"startPoint":{"x":27.6226685879999,"y":49.2865301220001,"z":0.0},"endPoint":{"x":-130.987358832,"y":49.2865301220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":8,"startPoint":{"x":-130.987358832,"y":49.2865301220001,"z":0.0},"endPoint":{"x":55.0366349159999,"y":-173.942262378,"z":186.023993748},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":9,"startPoint":{"x":55.0366349159999,"y":-173.942262378,"z":186.023993748},"endPoint":{"x":250.806443052,"y":-173.942262378,"z":186.023993748},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null}]},"interiorRings":[]},"obstructions":null,"penetrations":null},{"id":2,"area":846.2959062723575,"pitchAngle":39.80557109206678,"azimuthAngle":157.0,"azimuthVector":{"x":8.15589599118937E-13,"y":-1.0,"z":0.0},"roofMaterialType":"CompShingle","centroid":{"x":40.73557074093976,"y":-260.9491600545,"z":113.51824568538056},"coordinateSystem":{"xAxis":{"x":1.0,"y":8.153675545140119E-13,"z":0.0},"yAxis":{"x":-6.263827060728681E-13,"y":0.7682212795997437,"z":0.6401843996616384},"zAxis":{"x":5.22127737882233E-13,"y":-0.6401843996616384,"z":0.7682212795997437}},"polygon":{"exteriorRing":{"windingDirection":null,"edges":[{"id":10,"startPoint":{"x":55.0366349159999,"y":-173.942262378,"z":186.023993748},"endPoint":{"x":250.806443052,"y":-173.942262378,"z":186.023993748},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":11,"startPoint":{"x":250.806443052,"y":-173.942262378,"z":186.023993748},"endPoint":{"x":436.830436812,"y":-397.171054878,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":12,"startPoint":{"x":436.830436812,"y":-397.171054878,"z":0.0},"endPoint":{"x":200.222138112,"y":-184.223586042,"z":177.456224028},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":13,"startPoint":{"x":200.222138112,"y":-184.223586042,"z":177.456224028},"endPoint":{"x":-36.3861605880002,"y":-397.171054878,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":14,"startPoint":{"x":-36.3861605880002,"y":-397.171054878,"z":0.0},"endPoint":{"x":-395.356252476,"y":-397.171054878,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":15,"startPoint":{"x":-395.356252476,"y":-397.171054878,"z":0.0},"endPoint":{"x":-233.60219204848147,"y":-181.986002502,"z":179.3208769790444},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":16,"startPoint":{"x":-233.60219204848147,"y":-181.986002502,"z":179.3208769790444},"endPoint":{"x":48.3335181479998,"y":-181.986002502,"z":179.32087698},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":17,"startPoint":{"x":48.3335181479998,"y":-181.986002502,"z":179.32087698},"endPoint":{"x":55.0366349159999,"y":-173.942262378,"z":186.023993748},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null}]},"interiorRings":[]},"obstructions":null,"penetrations":null},{"id":3,"area":28.861144629405693,"pitchAngle":44.99999999999999,"azimuthAngle":247.0,"azimuthVector":{"x":-1.0,"y":-2.7597632959810743E-14,"z":0.0},"roofMaterialType":"CompShingle","centroid":{"x":-39.651141150000086,"y":-68.36067122099995,"z":91.336217682},"coordinateSystem":{"xAxis":{"x":2.7375588354885712E-14,"y":-1.0,"z":0.0},"yAxis":{"x":0.707106781186528,"y":1.935746416471063E-14,"z":0.707106781186567},"zAxis":{"x":-0.707106781186567,"y":-1.9514473410580082E-14,"z":0.707106781186528}},"polygon":{"exteriorRing":{"windingDirection":null,"edges":[{"id":18,"startPoint":{"x":-130.987358832,"y":33.1990498740001,"z":0.0},"endPoint":{"x":48.3335181479998,"y":-181.986002502,"z":179.32087698},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":19,"startPoint":{"x":48.3335181479998,"y":-181.986002502,"z":179.32087698},"endPoint":{"x":55.0366349159999,"y":-173.942262378,"z":186.023993748},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":20,"startPoint":{"x":55.0366349159999,"y":-173.942262378,"z":186.023993748},"endPoint":{"x":-130.987358832,"y":49.2865301220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":21,"startPoint":{"x":-130.987358832,"y":49.2865301220001,"z":0.0},"endPoint":{"x":-130.987358832,"y":33.1990498740001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null}]},"interiorRings":[]},"obstructions":null,"penetrations":null},{"id":4,"area":108.13850078904346,"pitchAngle":45.00000000322409,"azimuthAngle":247.0,"azimuthVector":{"x":-1.0,"y":0.0,"z":0.0},"roofMaterialType":"CompShingle","centroid":{"x":80.93547001199995,"y":36.945236517000104,"z":53.31280143},"coordinateSystem":{"xAxis":{"x":-2.220446049250313E-16,"y":-1.0,"z":0.0},"yAxis":{"x":0.7071067811467577,"y":-1.570092458595424E-16,"z":0.7071067812263372},"zAxis":{"x":-0.7071067812263372,"y":0.0,"z":0.7071067811467577}},"polygon":{"exteriorRing":{"windingDirection":null,"edges":[{"id":22,"startPoint":{"x":27.6226685879999,"y":49.2865301220001,"z":0.0},"endPoint":{"x":27.6226685879999,"y":88.5793046220001,"z":0.0},"bearingVector":null,"angleBetweenBearingVectorAndUpVector":0.0,"angleBetweenBearingVectorAndRightVector":0.0,"edgeCondition":"none","sidingMaterial":null},{"id":23,"startPoint":{"x":27.6226685879999,"y":88.5793046220001,"z":0.0},"endPoint":{"x":134.248271436,"y":
